import { ShowcaseProduct } from "./types";

export const SHOWCASE_PRODUCTS: ShowcaseProduct[] = [
  {
    id: "super-seeder",
    numericIndex: "01",
    title: "Super Seeder",
    category: "Tractor-Driven Equipments",
    categorySlug: "tractor-attachments",
    productSlug: "tractor-attachments",
    tagline: "Single-Pass Combined Tillage & Precision Grain Seeding",
    badge: "Tractor PTO Implements",
    bgWatermark: "SUPER SEEDER",
    accentColor: "#C40000",
    rfqDefaults: {
      productId: "ko-rotavator",
      productName: "KOREVA - Super Seeder (SUPER 11 / SUPER 13)",
      categoryName: "Tractor Attachments",
    },
    variants: [
      {
        id: "super-11",
        name: "SUPER 11",
        code: "SUPER 11",
        tagline: "11-Row High Productivity Model",
        image: "/products/Koreva Super Seeder.webp",
        imageAlt: "Koreva 9 Heavy-Duty Super Seeder 11 Row Agriculture Implement",
        badge: "50-55 HP Required",
        keyStats: [
          { label: "Working Width", value: "2082 mm", sub: "Effective tillage swath" },
          { label: "Tractor Power", value: "50-55 HP", sub: "Standard PTO coupling" },
          { label: "Blade Fleet", value: "54 Blades", sub: "Heat-treated J/F type" },
          { label: "Machine Weight", value: "970 Kg", sub: "Structural alloy steel" },
        ],
      },
      {
        id: "super-13",
        name: "SUPER 13",
        code: "SUPER 13",
        tagline: "13-Row Maximum Swath Enterprise Model",
        image: "/products/Koreva Super Seeder.webp",
        imageAlt: "Koreva 9 Heavy-Duty Super Seeder 13 Row Wide Swath Farm Implement",
        badge: "55-60 HP Required",
        keyStats: [
          { label: "Working Width", value: "2438 mm", sub: "Extra-wide working swath" },
          { label: "Tractor Power", value: "55-60 HP", sub: "Heavy tractor PTO" },
          { label: "Blade Fleet", value: "60 Blades", sub: "High-density soil cutting" },
          { label: "Machine Weight", value: "1050 Kg", sub: "Reinforced high-load frame" },
        ],
      },
    ],
    specs: [
      { label: "Working Width", variant1Value: "2082 mm", variant2Value: "2438 mm", highlight: true },
      { label: "HP Required", variant1Value: "50 - 55 HP", variant2Value: "55 - 60 HP", highlight: true },
      { label: "No. of Blades", variant1Value: "54 Blades", variant2Value: "60 Blades" },
      { label: "Type of Blade", variant1Value: "J/F Type Boron Steel", variant2Value: "J/F Type Boron Steel" },
      { label: "Gear Box", variant1Value: "Multi Speed Heavy-Duty", variant2Value: "Multi Speed Heavy-Duty" },
      { label: "Side Drive", variant1Value: "Enclosed Gear Drive", variant2Value: "Enclosed Gear Drive" },
      { label: "No. of Rows", variant1Value: "11 Rows", variant2Value: "13 Rows", highlight: true },
      { label: "Overall Weight", variant1Value: "970 Kg", variant2Value: "1050 Kg" },
    ],
  },
  {
    id: "power-weeder",
    numericIndex: "02",
    title: "Power Weeder",
    category: "Self-Propelled Machinery",
    categorySlug: "self-propelled-machinery",
    productSlug: "self-propelled-machinery",
    tagline: "All-Terrain Soil De-Weeding with 3-Speed Gearbox",
    badge: "Direct Gear-Driven Rotary",
    bgWatermark: "POWER WEEDER",
    accentColor: "#C40000",
    rfqDefaults: {
      productId: "ko-weeder-vijay",
      productName: "KOREVA - Power Weeder (DHURANDHAR & VIJAY Series)",
      categoryName: "Self-Propelled Machinery",
    },
    variants: [
      {
        id: "dhurandhar",
        name: "KO-1080 DHURANDHAR",
        code: "DHURANDHAR",
        tagline: "212 CC Compact Agile Inter-Crop Cultivator",
        image: "/products/Koreva Dhurandhar.webp",
        imageAlt: "Koreva KO-1080 Dhurandhar 7HP Gasoline Power Weeder",
        badge: "7.0 HP Gasoline",
        keyStats: [
          { label: "Engine Power", value: "7.0 HP", sub: "170F 4-Stroke OHV Engine" },
          { label: "Displacement", value: "212 CC", sub: "Fuel efficient air-cooled" },
          { label: "Tilling Depth", value: "5 - 8 Inches", sub: "Deep soil aeration" },
          { label: "Machine Weight", value: "90 Kg", sub: "Agile single-operator use" },
        ],
      },
      {
        id: "vijay",
        name: "KO-1110 VIJAY",
        code: "VIJAY",
        tagline: "270 CC Heavy-Duty High-Torque Soil Master",
        image: "/products/Koreva Vijay.webp",
        imageAlt: "Koreva KO-1110 Vijay 7.8HP High Torque Heavy Power Weeder",
        badge: "7.8 HP Heavy Series",
        keyStats: [
          { label: "Engine Power", value: "7.8 HP", sub: "177F High Torque Engine" },
          { label: "Displacement", value: "270 CC", sub: "Heavy duty commercial grade" },
          { label: "Tilling Depth", value: "5 - 8 Inches", sub: "Deep root disruption" },
          { label: "Machine Weight", value: "102 Kg", sub: "High-traction ground pressure" },
        ],
      },
    ],
    specs: [
      { label: "Engine Type", variant1Value: "170F Gasoline (4-Stroke)", variant2Value: "177F Gasoline (4-Stroke)", highlight: true },
      { label: "Rated Power", variant1Value: "7.0 HP", variant2Value: "7.8 HP", highlight: true },
      { label: "Engine Displacement", variant1Value: "212 CC", variant2Value: "270 CC", highlight: true },
      { label: "No. of Blades", variant1Value: "32 Blades", variant2Value: "32 Blades" },
      { label: "No. of Gears", variant1Value: "3 (2 Forward + 1 Reverse)", variant2Value: "3 (2 Forward + 1 Reverse)" },
      { label: "Tyre Size", variant1Value: "4.00 - 8 Tubeless", variant2Value: "4.00 - 8 Tubeless" },
      { label: "Tilling Depth", variant1Value: "5 - 8 Inches", variant2Value: "5 - 8 Inches" },
      { label: "Transmission Type", variant1Value: "Direct Gear Driven", variant2Value: "Direct Gear Driven" },
      { label: "Overall Weight", variant1Value: "90 Kg", variant2Value: "102 Kg" },
    ],
  },
  {
    id: "reaper-binder",
    numericIndex: "03",
    title: "Reaper Binder",
    category: "Tractor-Driven Equipments",
    categorySlug: "tractor-attachments",
    productSlug: "tractor-attachments",
    tagline: "Precision Crop Harvesting & Automatic Twine Sheaf Binding",
    badge: "Tractor PTO Implements",
    bgWatermark: "REAPER BINDER",
    accentColor: "#C40000",
    rfqDefaults: {
      productId: "ko-reaper-binder",
      productName: "KOREVA - Reaper Binder (KOS-RBD)",
      categoryName: "Tractor Attachments",
    },
    variants: [
      {
        id: "kos-rbd",
        name: "KOS-RBD",
        code: "KOS-RBD",
        tagline: "35 HP+ Tractor Driven Heavy Wheat Harvester & Binder",
        image: "/products/Koreva Reaper Binder.webp",
        imageAlt: "Koreva KOS-RBD Tractor Driven Reaper Binder Implement",
        badge: "35 HP and Above",
        keyStats: [
          { label: "Working Width", value: "2150 mm", sub: "Wide harvest sweep" },
          { label: "Rec. PTO RPM", value: "540 RPM", sub: "Standard tractor PTO" },
          { label: "HP Required", value: "35 HP+", sub: "Medium tractor compatible" },
          { label: "Machine Weight", value: "660 Kg", sub: "Balanced forged chassis" },
        ],
      },
    ],
    specs: [
      { label: "Working Width", values: ["2150 mm"], highlight: true },
      { label: "Rec. PTO RPM", values: ["540 RPM"] },
      { label: "Length", values: ["1325 mm"] },
      { label: "Width", values: ["2400 mm"] },
      { label: "Height", values: ["750 mm"] },
      { label: "Hp Required", values: ["35 HP and Above"], highlight: true },
      { label: "Crop Rec. for Harvesting", values: ["Wheat"], highlight: true },
      { label: "Machine Weight", values: ["660 Kg"] },
    ],
  },
  {
    id: "straw-reaper",
    numericIndex: "04",
    title: "Straw Reaper",
    category: "Tractor-Driven Equipments",
    categorySlug: "tractor-attachments",
    productSlug: "tractor-attachments",
    tagline: "Dual-Action Stubble Recovery & Fine Fodder Threshing System",
    badge: "Heavy-Duty Field Thresher",
    bgWatermark: "STRAW REAPER",
    accentColor: "#C40000",
    rfqDefaults: {
      productId: "ko-straw-reaper",
      productName: "KOREVA - Straw Reaper (KOR-56 / KOR-61)",
      categoryName: "Tractor Attachments",
    },
    variants: [
      {
        id: "kor-56",
        name: "KOR-56",
        code: "KOR-56",
        tagline: "56\" Heavy Chassis with 88\" Cutter Bar Standard",
        image: "/products/Straw reaper.webp",
        imageAlt: "Koreva KOR-56 Heavy Duty Straw Reaper Field Implement",
        badge: "50 HP+ Required",
        keyStats: [
          { label: "Chasis", value: "56\"", sub: "Rigid heavy box frame" },
          { label: "Cutter Bar", value: "88\"", sub: "31 cutter bar blades" },
          { label: "Thresher Blades", value: "288 Blades", sub: "Ultrafine pulverized straw" },
          { label: "Tractor Power", value: "50 HP+", sub: "Heavy tractor PTO" },
        ],
      },
      {
        id: "kor-61",
        name: "KOR-61",
        code: "KOR-61",
        tagline: "61\" Extra-Wide Chassis with 93\" Cutter Bar Enterprise",
        image: "/products/Straw reaper.webp",
        imageAlt: "Koreva KOR-61 High Capacity Enterprise Straw Reaper",
        badge: "55 HP+ Required",
        keyStats: [
          { label: "Chasis", value: "61\"", sub: "Maximum capacity frame" },
          { label: "Cutter Bar", value: "93\"", sub: "33 cutter bar blades" },
          { label: "Thresher Blades", value: "320 Blades", sub: "High throughput shredding" },
          { label: "Tractor Power", value: "55 HP+", sub: "Heavy-duty PTO drive" },
        ],
      },
    ],
    specs: [
      { label: "Chasis", values: ["56\"", "61\""], highlight: true },
      { label: "Cutter Bar", values: ["88\"", "93\""], highlight: true },
      { label: "Diameter of Thresher Drum", values: ["785 mm", "785 mm"] },
      { label: "No. of Blades in Thresher", values: ["288", "320"], highlight: true },
      { label: "No. of Blades in Basket", values: ["37", "41"] },
      { label: "No. of Blades in Cutter Bar", values: ["31", "33"] },
      { label: "Tyres", values: ["6x50x20, 7x19", "6x50x20, 7x19"] },
      { label: "Weight", values: ["1955 Kgs (approx.)", "2125 Kgs (approx.)"] },
      { label: "Tractor Power", values: ["50 HP+", "55 HP+"], highlight: true },
    ],
  },
  {
    id: "pulverizer",
    numericIndex: "05",
    title: "Pulverizer",
    category: "Food Processing Unit",
    categorySlug: "food-processing-units",
    productSlug: "food-processing-units",
    tagline: "Industrial Electric Flour & Grain Micro-Grinding Mill",
    badge: "Food-Grade Stainless / MS",
    bgWatermark: "PULVERIZER",
    accentColor: "#C40000",
    rfqDefaults: {
      productId: "ko-pulverizer",
      productName: "KOREVA - Industrial Food Processing Pulverizer (2HP / 3HP / 5HP)",
      categoryName: "Food Processing Units",
    },
    variants: [
      {
        id: "grah-laxmi-2hp",
        name: "KO-1170 GRAH LAXMI",
        code: "2 HP",
        tagline: "2 HP Single-Phase Commercial Grain Mill",
        image: "/products/Pulverizer.webp",
        imageAlt: "Koreva KO-1170 Grah Laxmi 2HP Electric Pulverizer",
        badge: "2 HP Single Phase",
        keyStats: [
          { label: "Motor Power", value: "2 HP", sub: "Electric 220V Single-Phase" },
          { label: "Grinding Output", value: "25-36 kg/hr", sub: "Fine grain flour output" },
          { label: "Rotor Speed", value: "2800 RPM", sub: "1140 or 2800 RPM rotor" },
          { label: "Machine Weight", value: "55 KG", sub: "Compact footprint" },
        ],
      },
      {
        id: "pulverizer-3hp",
        name: "3 HP PULVERIZER",
        code: "3 HP",
        tagline: "3 HP High-Torque Multi-Crop Grain Crusher",
        image: "/products/Pulverizer.webp",
        imageAlt: "Koreva 3HP Heavy Duty Food Processing Pulverizer",
        badge: "3 HP Electric",
        keyStats: [
          { label: "Motor Power", value: "3 HP", sub: "Electric 220V Single-Phase" },
          { label: "Grinding Output", value: "25-36 kg/hr", sub: "High throughput milling" },
          { label: "Rotor Speed", value: "2800 RPM", sub: "1140 or 2800 RPM rotor" },
          { label: "Machine Weight", value: "65 KG", sub: "Reinforced chassis" },
        ],
      },
      {
        id: "pulverizer-5hp",
        name: "5 HP PULVERIZER",
        code: "5 HP",
        tagline: "5 HP Heavy Industrial Continuous Processing Mill",
        image: "/products/Pulverizer.webp",
        imageAlt: "Koreva 5HP Industrial Heavy Duty Food Pulverizer",
        badge: "5 HP Electric",
        keyStats: [
          { label: "Motor Power", value: "5 HP", sub: "Electric 220V Single-Phase" },
          { label: "Grinding Output", value: "25-36 kg/hr", sub: "Commercial batch volume" },
          { label: "Rotor Speed", value: "2800 RPM", sub: "1140 or 2800 RPM rotor" },
          { label: "Machine Weight", value: "90 KG", sub: "Heavy vibration-free base" },
        ],
      },
    ],
    specs: [
      { label: "Motor Power", values: ["2 HP (Electric)", "3 HP (Electric)", "5 HP (Electric)"], highlight: true },
      { label: "Electricity", values: ["220V & Single Phase", "220V & Single Phase", "220V & Single Phase"] },
      { label: "Power Use", values: ["2 - 2.5 kW/hr", "2 - 2.5 kW/hr", "2 - 2.5 kW/hr"] },
      { label: "Grinding / Production Capacity", values: ["25-36 kg/hr", "25-36 kg/hr", "25-36 kg/hr"], highlight: true },
      { label: "Speed", values: ["1140 / 2800 RPM", "1140 / 2800 RPM", "1140 / 2800 RPM"] },
      { label: "Machine Weight", values: ["55 KG", "65 KG", "90 KG"] },
      { label: "Material", values: ["SS or MS", "SS or MS", "SS or MS"], highlight: true },
    ],
  },
];
